<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        /**
         * 
        */


    </script>
</head>

<body>
    <!-- 
       async 帮助我们用简洁的语法获得一个promise 对象
            let promise=new Promise(function(){})
            async function aaa(){}
            1、async 用户标识函数的 async函数返回的结果就是一个promise
            2、方法如果正常return结果，promise状态时resolved return后的结果是成功方法的返回值
            3、方法中出现了异常，则返回的promise就是一个失败状态
            4、async函数返回的结果如果是一个promise,则状态由内部的promise决定

       await 帮助我们获取promise 成功状态返回值的关键字
            1、await右边如果是一个普通值，则直接返回该值 如果右边是promise，返回promise状态成功返回的结果
                   let res = await "张三"
                   let res = await Promise.resolve("张三")
                       res = "张三"
            2、await右边如果是一个失败状态的promise 那么await会直接抛异常
            3、await关机字必须在async修饰的函数中使用，async函数中可以没有await
            4、await后边的代码会等待await执行完毕继续运行
     -->
    <script>
        async function fun1() {
            //return 10
            //throw new Error("something wrong")
            let promise = Promise.reject("heihei")
            return promise
        }
        let promise = fun1()
        promise.then(
            function (value) {
                console.log('success:' + value)
            }
        ).catch(
            function (value) {
                console.log("fail:" +value)
            }
        )
    </script>
</body>

</html>